% amplitude distortion
a = ones(1,10);
b = zeros(1,10);
c = [ a b a b];
subplot(2,4,1);
plot(c);
ylabel('original signal');
Aspectrum = abs(fft(c));
subplot(2,4,2);
plot(Aspectrum);
ylabel('amplitude spectrum of undistorted signal');
r = rand(size(Aspectrum));
Aspectrum = Aspectrum.*r;
subplot(2,4,3);
plot(Aspectrum);
ylabel('amplitude spectrum of distorted signal');
d = ifft(Aspectrum);
subplot(2,4,4);
plot(d);
ylabel('distorted signal');
%phase distortion
Phasespectrum = phase(fft(c));
subplot(2,4,5);
plot(Phasespectrum);
ylabel('phase spectrum of undistorted signal');
r2 = rand(size(Phasespectrum));
Phasespectrum = Phasespectrum.*r2;
subplot(2,4,6);
plot(Phasespectrum);
ylabel('phase spectrum distorted signal');
%Distortion caused by band limited channel (ISI)
x = [a b a b a b a b a b];
figure(2);
subplot(4,1,1);
plot(x);
xlabel('original signal');
fftx=fft(x,1024);
temp=fftshift(fftx);
subplot(4,1,2);
plot(abs(temp));
xlabel('original spectrum');
temp(1:400)=0;
temp(600:1000)=0;
subplot(4,1,3);
plot(abs(temp));
xlabel('band limited spectrum');
subplot(4,1,4);
plot(abs(ifft(temp))),axis([0 100 0 1.5]) ;
xlabel('distorted signal');